### ISSUE TITLE
Receiving a failure during startup and a question

### ISSUE THREAD

**Issue by bigtfromaz** [27Bslash6/docker#19]
Please forgive me if this is a dumb question.  I am testing the feasibility of using your image to host a local CA here at my small company.  My container configuration is attached.  It's a pure sandbox so I can easily make changes.

[OpenSSL.txt](https://github.com/27Bslash6/docker/files/2236869/OpenSSL.txt)

I created a user on the host named openSSL(1027/100,101).  It is in the users and administrators groups.  It's the id I want the service process to run as...  During startup, I am receiving a warning:

`* [WARNING] group found with gid 100 `
Are you trying to create users on the host or in a datastore somewhere?

 and this error:

`nginx: [emerg] getgrnam("openSSL") failed in /etc/nginx/nginx.conf:1`

Any thought regarding what I have done wrong?

And...I have another question.  I noticed a message indicating that he CA key is being stored under /etc which is not mapped outside the container.  Does this mean deleting the container will wipe out the CA?

Any help you might offer would be greatly appreciated.

**Comment by 27Bslash6** [comment]
Hiya, no dumb questions etc etc.

1. Users are created on the host, and the warning you're seeing is that a group exists with the GID 100 - 'users'. You can ignore this if that's your expected behaviour. The user logic is in: https://github.com/27Bslash6/docker/blob/master/nginx-pagespeed/bin/add_user.sh

2. See: https://serverfault.com/questions/742482/getgrnamuser-failed-in-etc-nginx-nginx-conf#742485 . Since you haven't specified an additional APP_GROUP, it defaults to 'users' but nginx expects there to be a group 'openSSL' in your case. May be worth adding ${APP_GROUP:-$DEFAULT_APP_GROUP} to nginx's users directive to support your use case.

3. See: https://github.com/27Bslash6/docker/blob/master/nginx-pagespeed/etc/service/nginx/run#L21 for the SSL certificate generation.  Yes, the cert is considered ephemeral and will be rebuilt each time you recreate the container. If persisting the self-signed certificate is required you might consider mapping `/etc/nginx/ssl/` folder to a local directory.

**Comment by bigtfromaz** [comment]
That's what I needed to know.  Thanks
